version: '3.4'

services:
  app:
    image: bphung1/ebookhubmvc:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 8
    ports:
      - 9000:443
    volumes:
      - /c/Users/bphun/.aspnet/https:/https/
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: SomePassword
  theapi:
    image: bphung1/ebookhubapi:latest
    deploy:
      replicas: 2
    volumes:
      - /c/Users/bphun/.aspnet/https:/https/
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: SomePassword
  visualizer:
    image: dockersamples/visualizer
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
