version: '3.4'

services:
  app:
    image: ebookhubmvc
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 2000s
        max_attempts: 8
  theapi:
    image: ebookhubapi
    deploy:
      replicas: 2